import './globals.css'
import { Inter } from 'next/font/google'
import ReduxProvider from '@/redux/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Akash Kr. Verma',
  description: 'This Portfolio is generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  )
}
